options:
  openstack-origin-git:
    default:
    type: string
    description: |
      Specifies a YAML-formatted dictionary listing the git
      repositories and branches from which to install OpenStack and
      its dependencies.

      When openstack-origin-git is specified, openstack-specific
      packages will be installed from source rather than from the
      the nova-compute charm's openstack-origin repository.

      Note that the installed config files will be determined based on
      the OpenStack release of the nova-compute charm's openstack-origin
      option.

      For more details see README.md.
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  data-port:
    type: string
    default:
    description: |
      Space-delimited list of bridge:port mappings. Ports will be added to
      their corresponding bridge. The bridges will allow usage of flat or
      VLAN network types with Neutron and should match this defined in
      bridge-mappings.
  disable-security-groups:
    type: boolean
    default: false
    description: |
      Disable neutron based security groups - setting this configuration option
      will override any settings configured via the neutron-api charm.
      .
      BE CAREFUL - this option allows you to disable all port level security within
      an OpenStack cloud.
  bridge-mappings:
    type: string
    default: 'physnet1:br-data'
    description: |
      Space-delimited list of ML2 data bridge mappings with format
      <provider>:<bridge>.
  flat-network-providers:
    type: string
    default:
    description: |
      Space-delimited list of Neutron flat network providers.
  vlan-ranges:
    type: string
    default: "physnet1:1000:2000"
    description: |
      Space-delimited list of Neutron network-provider & vlan-id-ranges using
      the following format "<provider>:<start>:<end> ...".
  # Network configuration options
  # by default all access is over 'private-address'
  os-data-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Data network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for tenant network traffic in overlay
      networks.
  ext-port:
    type: string
    default:
    description: |
      A space-separated list of external ports to use for routing of instance
      traffic to the external public network. Valid values are either MAC
      addresses (in which case only MAC addresses for interfaces without an IP
      address already assigned will be used), or interfaces (eth0)

