options:
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
  use-syslog:
    type: boolean
    default: False
    description: |
      By default, all services will log into their corresponding log files.
      Setting this to True will force all services to log to the syslog.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  data-port:
    type: string
    default:
    description: |
      The data port will be added to br-data and will allow usage of flat or VLAN
      network types
  disable-security-groups:
    type: boolean
    default: false
    description: |
      Disable neutron based security groups - setting this configuration option
      will override any settings configured via the neutron-api charm.
      .
      BE CAREFUL - this option allows you to disable all port level security within
      an OpenStack cloud.
  bridge-mappings:
    type: string
    default: 'physnet1:br-data'
    description: |
      Space-separated list of ML2 data bridge mappings with format
      <provider>:<bridge>.
  # Network configuration options
  # by default all access is over 'private-address'
  os-data-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Data network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for tenant network traffic in overlay
      networks.
  phy-nics:
    type: string
    default:
    description: |
      A space-separated list of NICs that we want phy-nic-mtu applied to.
  phy-nic-mtu:
    type: int
    default: 0
    description: |
      To improve network performance of VM, sometimes we should keep VM MTU as
      1500 and use charm to modify MTU of tunnel nic more than 1500 (e.g. 1546
      for GRE). A value of zero means no mtu will be set/modified.
  network-device-mtu:
    type: int
    default: 0
    description: |
      The MTU size for the interfaces managed by neutron. If set to 0, no value
      will be applied.
